// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/baizhigit/go-ms-examples/utest_mocks/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewUFORepository creates a new instance of UFORepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUFORepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UFORepository {
	mock := &UFORepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UFORepository is an autogenerated mock type for the UFORepository type
type UFORepository struct {
	mock.Mock
}

type UFORepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UFORepository) EXPECT() *UFORepository_Expecter {
	return &UFORepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UFORepository
func (_mock *UFORepository) Create(ctx context.Context, info model.SightingInfo) (string, error) {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SightingInfo) (string, error)); ok {
		return returnFunc(ctx, info)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SightingInfo) string); ok {
		r0 = returnFunc(ctx, info)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.SightingInfo) error); ok {
		r1 = returnFunc(ctx, info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UFORepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UFORepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - info model.SightingInfo
func (_e *UFORepository_Expecter) Create(ctx interface{}, info interface{}) *UFORepository_Create_Call {
	return &UFORepository_Create_Call{Call: _e.mock.On("Create", ctx, info)}
}

func (_c *UFORepository_Create_Call) Run(run func(ctx context.Context, info model.SightingInfo)) *UFORepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.SightingInfo
		if args[1] != nil {
			arg1 = args[1].(model.SightingInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFORepository_Create_Call) Return(s string, err error) *UFORepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UFORepository_Create_Call) RunAndReturn(run func(ctx context.Context, info model.SightingInfo) (string, error)) *UFORepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UFORepository
func (_mock *UFORepository) Delete(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UFORepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UFORepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFORepository_Expecter) Delete(ctx interface{}, uuid interface{}) *UFORepository_Delete_Call {
	return &UFORepository_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *UFORepository_Delete_Call) Run(run func(ctx context.Context, uuid string)) *UFORepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFORepository_Delete_Call) Return(err error) *UFORepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UFORepository_Delete_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *UFORepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UFORepository
func (_mock *UFORepository) Get(ctx context.Context, uuid string) (model.Sighting, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Sighting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Sighting, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Sighting); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Sighting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UFORepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UFORepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFORepository_Expecter) Get(ctx interface{}, uuid interface{}) *UFORepository_Get_Call {
	return &UFORepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *UFORepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *UFORepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFORepository_Get_Call) Return(sighting model.Sighting, err error) *UFORepository_Get_Call {
	_c.Call.Return(sighting, err)
	return _c
}

func (_c *UFORepository_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Sighting, error)) *UFORepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UFORepository
func (_mock *UFORepository) Update(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error {
	ret := _mock.Called(ctx, uuid, updateInfo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.SightingUpdateInfo) error); ok {
		r0 = returnFunc(ctx, uuid, updateInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UFORepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UFORepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - updateInfo model.SightingUpdateInfo
func (_e *UFORepository_Expecter) Update(ctx interface{}, uuid interface{}, updateInfo interface{}) *UFORepository_Update_Call {
	return &UFORepository_Update_Call{Call: _e.mock.On("Update", ctx, uuid, updateInfo)}
}

func (_c *UFORepository_Update_Call) Run(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo)) *UFORepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.SightingUpdateInfo
		if args[2] != nil {
			arg2 = args[2].(model.SightingUpdateInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UFORepository_Update_Call) Return(err error) *UFORepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UFORepository_Update_Call) RunAndReturn(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error) *UFORepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
