// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/baizhigit/go-ms-examples/utest_mocks/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewUFOService creates a new instance of UFOService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUFOService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UFOService {
	mock := &UFOService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UFOService is an autogenerated mock type for the UFOService type
type UFOService struct {
	mock.Mock
}

type UFOService_Expecter struct {
	mock *mock.Mock
}

func (_m *UFOService) EXPECT() *UFOService_Expecter {
	return &UFOService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UFOService
func (_mock *UFOService) Create(ctx context.Context, info model.SightingInfo) (string, error) {
	ret := _mock.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SightingInfo) (string, error)); ok {
		return returnFunc(ctx, info)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.SightingInfo) string); ok {
		r0 = returnFunc(ctx, info)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.SightingInfo) error); ok {
		r1 = returnFunc(ctx, info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UFOService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UFOService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - info model.SightingInfo
func (_e *UFOService_Expecter) Create(ctx interface{}, info interface{}) *UFOService_Create_Call {
	return &UFOService_Create_Call{Call: _e.mock.On("Create", ctx, info)}
}

func (_c *UFOService_Create_Call) Run(run func(ctx context.Context, info model.SightingInfo)) *UFOService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.SightingInfo
		if args[1] != nil {
			arg1 = args[1].(model.SightingInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFOService_Create_Call) Return(s string, err error) *UFOService_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UFOService_Create_Call) RunAndReturn(run func(ctx context.Context, info model.SightingInfo) (string, error)) *UFOService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UFOService
func (_mock *UFOService) Delete(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UFOService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UFOService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFOService_Expecter) Delete(ctx interface{}, uuid interface{}) *UFOService_Delete_Call {
	return &UFOService_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *UFOService_Delete_Call) Run(run func(ctx context.Context, uuid string)) *UFOService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFOService_Delete_Call) Return(err error) *UFOService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UFOService_Delete_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *UFOService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UFOService
func (_mock *UFOService) Get(ctx context.Context, uuid string) (model.Sighting, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Sighting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Sighting, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Sighting); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Sighting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UFOService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UFOService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFOService_Expecter) Get(ctx interface{}, uuid interface{}) *UFOService_Get_Call {
	return &UFOService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *UFOService_Get_Call) Run(run func(ctx context.Context, uuid string)) *UFOService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UFOService_Get_Call) Return(sighting model.Sighting, err error) *UFOService_Get_Call {
	_c.Call.Return(sighting, err)
	return _c
}

func (_c *UFOService_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Sighting, error)) *UFOService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UFOService
func (_mock *UFOService) Update(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error {
	ret := _mock.Called(ctx, uuid, updateInfo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.SightingUpdateInfo) error); ok {
		r0 = returnFunc(ctx, uuid, updateInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UFOService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UFOService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - updateInfo model.SightingUpdateInfo
func (_e *UFOService_Expecter) Update(ctx interface{}, uuid interface{}, updateInfo interface{}) *UFOService_Update_Call {
	return &UFOService_Update_Call{Call: _e.mock.On("Update", ctx, uuid, updateInfo)}
}

func (_c *UFOService_Update_Call) Run(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo)) *UFOService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.SightingUpdateInfo
		if args[2] != nil {
			arg2 = args[2].(model.SightingUpdateInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UFOService_Update_Call) Return(err error) *UFOService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UFOService_Update_Call) RunAndReturn(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error) *UFOService_Update_Call {
	_c.Call.Return(run)
	return _c
}
