// Package weather_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package weather_v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// BadRequestError defines model for bad_request_error.
type BadRequestError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// GenericError defines model for generic_error.
type GenericError struct {
	// Code HTTP-код ошибки
	Code *int `json:"code,omitempty"`

	// Message Описание ошибки
	Message *string `json:"message,omitempty"`
}

// InternalServerError defines model for internal_server_error.
type InternalServerError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// NotFoundError defines model for not_found_error.
type NotFoundError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// UpdateWeatherRequest defines model for update_weather_request.
type UpdateWeatherRequest struct {
	// Temperature Температура в градусах Цельсия
	Temperature float32 `json:"temperature"`
}

// Weather defines model for weather.
type Weather struct {
	// City Название города
	City string `json:"city"`

	// Temperature Температура в градусах Цельсия
	Temperature float32 `json:"temperature"`

	// UpdatedAt Время последнего обновления данных
	UpdatedAt time.Time `json:"updated_at"`
}

// City defines model for city.
type City = string

// UpdateWeatherByCityJSONRequestBody defines body for UpdateWeatherByCity for application/json ContentType.
type UpdateWeatherByCityJSONRequestBody = UpdateWeatherRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetWeatherByCity request
	GetWeatherByCity(ctx context.Context, city City, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateWeatherByCityWithBody request with any body
	UpdateWeatherByCityWithBody(ctx context.Context, city City, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateWeatherByCity(ctx context.Context, city City, body UpdateWeatherByCityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetWeatherByCity(ctx context.Context, city City, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWeatherByCityRequest(c.Server, city)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateWeatherByCityWithBody(ctx context.Context, city City, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateWeatherByCityRequestWithBody(c.Server, city, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateWeatherByCity(ctx context.Context, city City, body UpdateWeatherByCityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateWeatherByCityRequest(c.Server, city, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetWeatherByCityRequest generates requests for GetWeatherByCity
func NewGetWeatherByCityRequest(server string, city City) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "city", runtime.ParamLocationPath, city)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/weather/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateWeatherByCityRequest calls the generic UpdateWeatherByCity builder with application/json body
func NewUpdateWeatherByCityRequest(server string, city City, body UpdateWeatherByCityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateWeatherByCityRequestWithBody(server, city, "application/json", bodyReader)
}

// NewUpdateWeatherByCityRequestWithBody generates requests for UpdateWeatherByCity with any type of body
func NewUpdateWeatherByCityRequestWithBody(server string, city City, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "city", runtime.ParamLocationPath, city)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/weather/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetWeatherByCityWithResponse request
	GetWeatherByCityWithResponse(ctx context.Context, city City, reqEditors ...RequestEditorFn) (*GetWeatherByCityResponse, error)

	// UpdateWeatherByCityWithBodyWithResponse request with any body
	UpdateWeatherByCityWithBodyWithResponse(ctx context.Context, city City, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateWeatherByCityResponse, error)

	UpdateWeatherByCityWithResponse(ctx context.Context, city City, body UpdateWeatherByCityJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateWeatherByCityResponse, error)
}

type GetWeatherByCityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Weather
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSONDefault  *GenericError
}

// Status returns HTTPResponse.Status
func (r GetWeatherByCityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWeatherByCityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateWeatherByCityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Weather
	JSON400      *BadRequestError
	JSON500      *InternalServerError
	JSONDefault  *GenericError
}

// Status returns HTTPResponse.Status
func (r UpdateWeatherByCityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateWeatherByCityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetWeatherByCityWithResponse request returning *GetWeatherByCityResponse
func (c *ClientWithResponses) GetWeatherByCityWithResponse(ctx context.Context, city City, reqEditors ...RequestEditorFn) (*GetWeatherByCityResponse, error) {
	rsp, err := c.GetWeatherByCity(ctx, city, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWeatherByCityResponse(rsp)
}

// UpdateWeatherByCityWithBodyWithResponse request with arbitrary body returning *UpdateWeatherByCityResponse
func (c *ClientWithResponses) UpdateWeatherByCityWithBodyWithResponse(ctx context.Context, city City, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateWeatherByCityResponse, error) {
	rsp, err := c.UpdateWeatherByCityWithBody(ctx, city, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateWeatherByCityResponse(rsp)
}

func (c *ClientWithResponses) UpdateWeatherByCityWithResponse(ctx context.Context, city City, body UpdateWeatherByCityJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateWeatherByCityResponse, error) {
	rsp, err := c.UpdateWeatherByCity(ctx, city, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateWeatherByCityResponse(rsp)
}

// ParseGetWeatherByCityResponse parses an HTTP response from a GetWeatherByCityWithResponse call
func ParseGetWeatherByCityResponse(rsp *http.Response) (*GetWeatherByCityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWeatherByCityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Weather
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest GenericError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateWeatherByCityResponse parses an HTTP response from a UpdateWeatherByCityWithResponse call
func ParseUpdateWeatherByCityResponse(rsp *http.Response) (*UpdateWeatherByCityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateWeatherByCityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Weather
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest GenericError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get weather data for a city
	// (GET /api/v1/weather/{city})
	GetWeatherByCity(w http.ResponseWriter, r *http.Request, city City)
	// Update or create weather data for a city
	// (PUT /api/v1/weather/{city})
	UpdateWeatherByCity(w http.ResponseWriter, r *http.Request, city City)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get weather data for a city
// (GET /api/v1/weather/{city})
func (_ Unimplemented) GetWeatherByCity(w http.ResponseWriter, r *http.Request, city City) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update or create weather data for a city
// (PUT /api/v1/weather/{city})
func (_ Unimplemented) UpdateWeatherByCity(w http.ResponseWriter, r *http.Request, city City) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWeatherByCity operation middleware
func (siw *ServerInterfaceWrapper) GetWeatherByCity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "city" -------------
	var city City

	err = runtime.BindStyledParameterWithOptions("simple", "city", chi.URLParam(r, "city"), &city, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "city", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWeatherByCity(w, r, city)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWeatherByCity operation middleware
func (siw *ServerInterfaceWrapper) UpdateWeatherByCity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "city" -------------
	var city City

	err = runtime.BindStyledParameterWithOptions("simple", "city", chi.URLParam(r, "city"), &city, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "city", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWeatherByCity(w, r, city)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/weather/{city}", wrapper.GetWeatherByCity)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/weather/{city}", wrapper.UpdateWeatherByCity)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYzW7jNhB+FYItsBfZlrPxRbekh9ZAD0GboECDwGCksaONRakU5cQIDOSn2xbYogsU",
	"vbaHHnrOj401NonzCsNX6JMUJKXYjp0utvUCWcAn2RI1/OabGc58OqJ+HCUxBy5T6h3RhAkWgQRh/vmh",
	"7OprAKkvwkSGMacexd/xHN/gJZ7jLQ5xQPAKR+oYR9jHc4dgH6/Va4JvcaRO8wdXOCL4Bs/xTh3jufoJ",
	"h/p19Ys6VSd67RCvcUhwhBd4iyO81BbGT/tmp1v1Su81InhnLWIfB9ShocaUMLlHHcpZBNSzuB0q4Lss",
	"FBBQT4oMHJr6exAx7RAcsihp66Vr7YiZxRE7/BJ4S+5Rr+q6Do1Cfv/fobKb6NWpFCFv0V6v55gt6xIi",
	"w9QBMLkHorHbbRSktUDqS5yAYJq5ekA9+jnIb+zS9e5nBco0iXkKxs6K6xriYy6Bm/dZkrRD31iovEh1",
	"AI4mHPlUQJN69JPKOIwV+zSt5Jgs2ukQ5hhIyJuxiIxxkma+D2nazNrtLhEgRQgdCGjPoasLBLXLgoaO",
	"C6SyAULEc+Gts4Dki0iJdFg7DCzG/A0NaXVhkHgsG80448HjgAq+AiYZacaCpAn4YTOEgOhwEx5LYkxo",
	"bLUF0hVyCYKzdiMF0QHxOMJ6vpDYhWOmAmiyrC0XhqgFHEToP45ki8NhAr6EoADRc2iaRRETXVsB5OAh",
	"nYzkJStZK6XedkE43TGFNj6TtueDGy+pGEO9HYcm2Zz620oCJmG2BE2urcdBd2E8ZWanRnEw5FtYwqYP",
	"pt4TPQOsB0/1BFhW2b9Vmc1zEgviC9C/3qfkjCkLROOcDZgeFIQuLBnalPXjAGYHhS82NzdKeg7APsGR",
	"6foX+BaH1Bk34FXda/PuqsPQAsNnBGnKWnNs4h94h0N1Mh4+HjFsUugrC9sjdW5yiNwfFMQmPZ1t7ZPl",
	"uW09G+PZuV8f774AX2qs07H6/9wskI1Z32bQz8/9BUa49sEiPLcaSez7mdDRW0BoH44GC0381Q9ES3Gw",
	"6yo308mzLb7P4wP+bGJOWQA5j3S4GY4kRKYHZ2KeW3/iAG/wDgdGGZyqM30leEnwSv/CvjrTTquXBP/C",
	"AV6rn9UJDtXrSZdXauWaQ/OK9mizHU9WNs+iXRAzHk7Cmude0TpnY/7+qmgqPv9NcjhPhsci8kGDyTlA",
	"flXHGooWbnc4Uid4jQPs4y0OrAycEHk40FxNSTz1coqrFXelVqq6pWpts+p6z13Pdb+lExA1jpIMI3h3",
	"QufdboLEKUdmU6BnTsdmPOvj2ka9kLmG2wstddUrok4mxeqNkbQP5aoM5WSVfg2iE/pA1jbq1KEdEKnd",
	"olp2y67mOk6AsySkHn1erpZdaoWnScQKS8JKp1oMeZUj7WNvqT2X2nM5FS+151J7LrXnx6k987tzJ2A7",
	"3vyAQxy+u92Sv49/szeu1Zn60Y4bejQbzhlDzH28Vd+bse2m2GX8VbkAqQv8sBSzJCzpKbkF3H459/fN",
	"4H7/LbhTNR4K04xpuZLstyp5N79v2Z0q7fX+CQAA//8jSYB8hRcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
