all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
force-file-write: true
structname: "{{.InterfaceName}}"
pkgname: "mocks"
recursive: false
template: testify
packages:
  github.com/baizhigit/go-ms-examples/utest_mocks/internal/service:
    config:
      include-interface-regex: ".*Service"

  github.com/baizhigit/go-ms-examples/utest_mocks/internal/repository:
    config:
      include-interface-regex: ".*Repository"